[package]
name = "poseidon-merkle-tree"
version = "0.1.0"
edition = "2024"

[dependencies]
ark-bn254 = "0.5.0"
light-poseidon = "0.3.0"
serde = { version = "1.0.219", features = ["derive"] }
thiserror = "2.0.12"
