[package]
name = "poseidon-merkle-tree"
version = "0.1.0"
edition = "2021"

[dependencies]
ark-bn254 = "0.5.0"
borsh = { version = "1.5.7", features = ["derive"] }
light-poseidon = "0.3.0"
thiserror = "2.0.12"
