[package]
name = "poseidon-merkle-tree"
version = "0.1.0"
edition = "2021"

[dependencies]
ark-bn254 = "0.5.0"
ark-ff = "0.5.0"
borsh = "0.10.4"
light-poseidon = "0.3.0"
once_cell = "1.21.3"
thiserror = "2.0.12"
